services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

# Notes:
# No need to use version at the begining of the compose file. The CLI infers supported features from your installed Docker/Compose so the version key is ignored.
# This docker-compose.yml file defines two containers web and db.
# depends_on ensures db contaienr starts first
# volumes: defines db_data for persistent MySQL storage.
# .:/app mounts current directory to /app for live code updates.  The syntax .:/app maps the current directory to /app using :
# MYSQL_DATABASE tells MySQL to automatically create a database named test_db
# In MYSQL_ROOT_PASSWORD example is just a paceholder for the admit password.
# mysql:8.0 is available for Apple Silicon (arm64). mysql:5.7 us only available for linux (amd64)
